export const ROLES = {
  USER: "USER",
  ADMINISTRATOR: "ADMINISTRATOR",
  KOMITE_PUSAT: "KOMITE_PUSAT",
  PENGELOLA_RISIKO_UKER: "PENGELOLA_RISIKO_UKER",
};

export const ASSET_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const PROCESS_BUSINESS_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const CONTEXT_TYPES = {
  ASSET: "ASSET",
  PROCESS: "PROCESS",
};

export const RISK_PROGRAM_STATUSES = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  CLOSED: "CLOSED",
  ARCHIVED: "ARCHIVED",
};

export const PROGRAM_FRAMEWORK_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const RISK_CONTEXT_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const WORKING_PAPER_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  REVISION: "REVISION",
  APPROVED: "APPROVED",
  LOCKED: "LOCKED",
};

export const CONTROL_EFFECTIVENESS = {
  ADEQUATE: "ADEQUATE",
  PARTIAL: "PARTIAL",
  INADEQUATE: "INADEQUATE",
};

export const ASSESSMENT_TYPES = {
  INHERENT: "INHERENT",
  RESIDUAL: "RESIDUAL",
};

export const TREATMENT_STATUSES = {
  PLANNED: "PLANNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  SUBMITTED_FOR_REVIEW: "SUBMITTED_FOR_REVIEW",
  VERIFIED: "VERIFIED",
};
