export const ROLES = {
  USER: "USER",
  ADMINISTRATOR: "ADMINISTRATOR",
  KOMITE_PUSAT: "KOMITE_PUSAT",
  PENGELOLA_RISIKO_UKER: "PENGELOLA_RISIKO_UKER",
};

export const ASSET_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const PROCESS_BUSINESS_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};

export const CONTEXT_TYPES = {
  ASSET: "ASSET",
  PROCESS: "PROCESS",
};

export const RISK_PROGRAM_STATUSES = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  CLOSED: "CLOSED",
  ARCHIVED: "ARCHIVED",
};

export const RISK_CONTEXT_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
};
